title: The Symbiosis of Deep Learning and Differential Equations (DLDE)
email: poli@stanford.edu
description: Website for workshop "The Symbiosis of Deep Learning and Differential Equations (DLDE)" at NeurIPS 2021
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
ga_id: UA-110470966-1
